[package]
name = "wasi_vercel_example"
version = "0.1.0"
authors = ["ubuntu"]
edition = "2018"

[[bin]]
name = "wasi_food_classify"
path = "src/main.rs"

[dependencies]
wasmedge_tensorflow_interface = "^0.2.0"

